repos:
  # Some useful built-in hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  # Ruff: linter + formatter + import sorter
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.8  # Use the latest Ruff version
    hooks:
      - id: ruff
        args: [--fix]  # auto-fix issues where possible
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2
    hooks:
      - id: mypy
        additional_dependencies:
          - types-requests  # example: add stub packages you need
