[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "qgis-tidy"
version = "0.1.0"
dependencies = ["lxml"]

[project.scripts]
qgis-tidy = "qgis_tidy.cli:main"